### ISSUE TITLE
Pipe error on lintserver

### ISSUE THREAD

**Issue by AntonioSaragga** [AtomLinter/linter-julia#42]
Hello
I am getting the following error message ENOENT on Atom 1.12.5
```
Error: connect ENOENT .\pipe\lintserver11208ZqSxlPblS5ngsock
Error: connect ENOENT \.\pipe\lintserver11208ZqSxlPblS5ngsock
at Object.exports._errnoException (util.js:1026:11)
at exports._exceptionWithHostPort (util.js:1049:20)
at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1081:14)
```

Any help would be much appreciated

**Comment by TeroFrondelius** [comment]
This is the error that lintserver() is not yet running. Go to the linter-julia setting and set the julia executable location and then press Ctrl + Shift + F5 (restart) actually try first to restart.  It might be enough. Also if the problem persists press Ctrl + Shift + I to see console log output. If you already posted the console output do you see the line lintserver() running pipe/port ...

**Comment by AntonioSaragga** [comment]
Thank you for your reply. Unfortunately I am still getting the same error as before. On the console output I also get the following: Uncaught SyntaxError: Unexpected end of JSON input VM1501:1 .

**Comment by TeroFrondelius** [comment]
See issue #38  for proposals. If you are really brave enough, uninstall linter-julia and install the master version (in install GUI just give the git repo address). The master version is totally rewritten and have fixed this issue. I haven't released it yet because I want to do more testing and possible even add the specs (automated testing). The master version currently assumes that command ´julia´ will start correct version of Julia, but this can be changed also from the settings.

**Comment by Arcanemagus** [comment]
Looks like the proposed fix in the `master` branch was released since the last comment with no further input, closing this issue and thanks for taking the time to file it!
