### ISSUE TITLE
Make a workaround to fix row numbers, when Lint.jl reports them wrong 

### ISSUE THREAD

**Issue by TeroFrondelius** [AtomLinter/linter-julia#7]
Maybe this can be fixed somehow in the linter-julia package. See description https://github.com/tonyhffong/Lint.jl/issues/54.

**Comment by Arcanemagus** [comment]
It seems that `Lint.jl` also quite often reports a range of `[[n,0], [n, 80]]` for a line when it can't determine an actual range. We could use [atom-linter::generateRange](https://github.com/steelbrain/atom-linter#api) in order to create a range that encompasses the code of the line when we see this.

**Comment by aminya** [comment]
Outdated after #119
